name: Start Docker Compose on Self-hosted Runner

on:
  workflow_dispatch:

jobs:
  run-docker-compose:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cleanup old containers and images (excluding MongoDB)
        run: |
          set +e  # Don’t fail if some don’t exist

          echo "Stopping and removing old containers..."
          sudo docker rm -f \
            user-management-service \
            note-management-service \
            note-management-microservice \
            notif-management-service \
            document-management-microservice \
            evaluation-feedback-service \
            event-repository-feature-crud-event \
            esprit-frontend

          echo "Removing old images..."
          sudo docker rmi -f \
            jobrane23/user-management-service \
            jobrane23/note-management-service:latest \
            jobrane23/note-management-microservice:latest \
            jobrane23/notif-management-service:latest \
            jobrane23/document-management-microservice:latest \
            jobrane23/evaluation-feedback-service:latest \
            jobrane23/event-repository-feature-crud-event:latest \
            jobrane23/esprit-frontend:latest

        continue-on-error: true

      - name: Ensure Docker Compose is installed
        run: sudo docker compose version

      - name: Start Docker Compose
        run: sudo docker compose -f docker-compose.yml up -d

      - name: Wait for containers to become healthy
        run: sleep 15

      - name: Show running containers
        run: sudo docker ps
