name: Test on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "This runs only on pushes to main branch"
