name: SonarQube Note Microservice

on:
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Maven settings for Nexus
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USER }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Note Microservice
        working-directory: note-managment-microservice
        run: mvn clean install -DskipTests

      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${SONAR_HOST_URL}" \
            -e SONAR_TOKEN="${SONAR_TOKEN}" \
            -v "${{ github.workspace }}/note-managment-microservice:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=note-management \
            -Dsonar.sources=/usr/src/src \
            -Dsonar.java.binaries=/usr/src/target/classes \
            -Dsonar.login="${SONAR_TOKEN}"

      - name: Deploy to Nexus
        working-directory: note-managment-microservice
        run: mvn deploy -DskipTests

      - name: Build Docker image
        working-directory: note-managment-microservice
        run: docker build -t note-management-service:latest .
