name: SonarQube Note Microservice

on:
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Maven settings for Nexus
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>1234</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Note Microservice
        working-directory: note-management-microservice
        run: mvn clean install -DskipTests

      - name: Run SonarQube scan
        working-directory: note-management-microservice
        run: |
          sudo docker run --rm \
            -e SONAR_HOST_URL="http://192.168.79.128:9000" \
            -e SONAR_TOKEN="sqa_6b79d9e85ab7e2eea7f917872766b9e6af8bd6c0" \
            -v "$PWD:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=note-managment \
            -Dsonar.sources=/usr/src/src \
            -Dsonar.java.binaries=/usr/src/target/classes \
            -Dsonar.host.url=http://192.168.79.128:9000 \
            -Dsonar.login=sqa_6b79d9e85ab7e2eea7f917872766b9e6af8bd6c0

      - name: Deploy to Nexus
        working-directory: note-management-microservice
        run: mvn deploy -DskipTests

      - name: Build Docker image
        working-directory: note-management-microservice
        run: sudo docker build -t jobrane23/note-management-service:latest .
      - name: Push Docker image
        run: |
          sudo docker login -u jobrane23 -p PI23381121
          sudo docker push jobrane23/note-management-service:latest
