name: CI/CD PI

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print greeting
        run: echo "Hello from self-hosted runner on $(hostname)"

      - name: Show current user and OS
        run: |
          whoami
          uname -a
