name: CI/CD

on:
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment info
        run: |
          echo "Running on $(hostname)"
          whoami
          uname -a

      - name: Run SonarQube scan
        run: |
          sudo docker run --rm \
            -e SONAR_HOST_URL="http://192.168.79.128:9000" \
            -e SONAR_TOKEN="sqa_6b79d9e85ab7e2eea7f917872766b9e6af8bd6c0" \
            -v "$PWD:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=my-project-key \
            -Dsonar.sources=/usr/src \
            -Dsonar.host.url=http://192.168.79.128:9000 \
            -Dsonar.login=$SONAR_TOKEN
