name: CI/CD

on:
  workflow_dispatch:   # allows manual trigger

jobs:
  sonar-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print environment info
        run: |
          echo "Running on $(hostname)"
          whoami
          uname -a

      - name: Run SonarQube scan
        run: |
          sudo docker run --rm \
            -e SONAR_HOST_URL="http://192.168.79.128:9000" \
            -e SONAR_LOGIN=squ_c33fe41d2ad2bc9d4c0745192539537d49a50fe9 \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=my-project-key \
            -Dsonar.sources=/usr/src
