name: SonarQube User Microservice

on:
  workflow_dispatch:

jobs:
  sonar-scan:
    runs-on: self-hosted

    steps:
      - name: Init BUILD_FAILED flag
        run: echo "BUILD_FAILED=0" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Maven settings for Nexus
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build User Microservice
        working-directory: user-managment-ms
        run: |
          mvn clean install -DskipTests || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Run SonarQube scan
        working-directory: user-managment-ms
        run: |
          sudo docker run --rm \
            -e SONAR_HOST_URL="http://192.168.79.129:9000" \
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
            -v "$PWD:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=user-management \
            -Dsonar.sources=/usr/src/src \
            -Dsonar.java.binaries=/usr/src/target/classes \
            -Dsonar.host.url=http://192.168.79.129:9000 \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}" || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Deploy to Nexus
        working-directory: user-managment-ms
        run: |
          mvn deploy -DskipTests || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Build Docker image
        working-directory: user-managment-ms
        run: |
          sudo docker build -t jobrane23/user-management-service:latest . || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | sudo docker login -u jobrane23 --password-stdin || echo "BUILD_FAILED=1" >> $GITHUB_ENV
          sudo docker push jobrane23/user-management-service:latest || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Download Trivy HTML template
        run: |
          curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Scan Docker image with Trivy and save report
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --format template \
            --template "@html.tpl" \
            -o trivy-report.html \
            --scanners vuln \
            --skip-db-update \
            --timeout 30m \
            jobrane23/user-management-service:latest || true

      - name: List report file
        run: ls -lh trivy-report.html

      - name: Setup Python and send email (if needed)
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python3 send_email.py || echo "BUILD_FAILED=1" >> $GITHUB_ENV

      - name: Set BUILD_STATUS env
        if: always()
        run: |
          if [ "$BUILD_FAILED" -eq "1" ]; then
            echo "BUILD_STATUS=fail" >> $GITHUB_ENV
          else
            echo "BUILD_STATUS=success" >> $GITHUB_ENV
          fi

      - name: Send Email Notification
        if: always()
        continue-on-error: true
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          BUILD_STATUS: ${{ env.BUILD_STATUS }}
        run: python3 sendBuildMail.py
